alias start='startxfce4'
alias shut='shutdown -h now'
alias weather='curl wttr.in'
alias covid='curl https://corona-stats.online/usa'
alias clock='ruby /home/$USER/.local/bin/term-clock.rb'
alias visu='catnip -b parec -d alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
